name: Pet Clinic Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  secret-scanning:
    name: Secret scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Truffle Hog scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: secret-scanning
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.25+8' 
          distribution: 'temurin'
      - name: Maven Build
        run: mvn clean package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact
          path: target/*.jar
      
  
