name: Pet Clinic Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - sbom-gen 
    paths-ignore:
      - README.md
      - .gitignore
jobs:
  sbom:
    name: SBOM generation
    runs-on: ubuntu-latest
    permissions:
     actions: read
     contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
